### ISSUE TITLE
底下有组件的话下拉的列表会被底下的组件挡住

### ISSUE THREAD

**Issue by StanLee12** [yylgit/react-native-select#1]
![image](https://cloud.githubusercontent.com/assets/19790418/19886490/5d389c32-a05e-11e6-8b02-ec16f7c0ec06.png)

**Comment by yylgit** [comment]
这个问题，之前我用zIndex解决，但是在android下面会有兼容问题，所以我现在把Select组件放在布局的后面，然后利用绝对定位定位到需要的位置，这样Select组件就会在最上面

**Comment by StanLee12** [comment]
@yylgit  了解，thanks
